create table public.units (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  unidade text null,
  tipologia text null,
  bloco text null,
  piso numeric null,
  "AHB" text null,
  "ABE" text null,
  preço numeric null,
  luz_natural numeric null,
  score numeric null,
  constraint units_pkey primary key (id)
) TABLESPACE pg_default;